[package]
name = "palette-gpui-prototype"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
gpui-component.workspace = true
gpui-base.workspace = true
palette-prototype-core.workspace = true
windows.workspace = true
