[package]
name = "komorebi-gui"
version = "0.1.42"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
komorebi-client = { path = "../komorebi-client", default-features = false }
komorebi-protocol = { path = "../komorebi-protocol" }
komorebi-shell = { path = "../komorebi-shell" }

eframe = { workspace = true }
egui_extras = { workspace = true }
random_word = { version = "0.5", features = ["en"] }
serde_json = { workspace = true }
thiserror = "2"
tokio = { version = "=1.53.1", features = ["macros", "rt-multi-thread", "sync"] }
windows-core = { workspace = true }
windows = { workspace = true }
