[package]
name = "decoration-compute-measure"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
decoration-compute-core = { path = "../core" }
decoration-compute-windows = { path = "../windows-adapter" }
particle-kernel.workspace = true
serde.workspace = true
serde_json.workspace = true
