[package]
name = "decoration-compute-windows"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
decoration-compute-core = { path = "../core" }
decoration-effect-core.workspace = true
particle-kernel.workspace = true
thiserror.workspace = true
windows.workspace = true
