#![allow(clippy::inline_always, clippy::ref_as_ptr)] // Generated by windows::core::implement.

use std::mem::size_of;
use std::sync::mpsc::{Receiver, Sender, channel};
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use serde::Serialize;
use windows::Win32::Foundation::{E_FAIL, E_POINTER};
use windows::Win32::Media::Audio::Endpoints::{
    IAudioEndpointVolume, IAudioEndpointVolumeCallback, IAudioEndpointVolumeCallback_Impl,
};
use windows::Win32::Media::Audio::{
    AUDIO_VOLUME_NOTIFICATION_DATA, IMMDeviceEnumerator, MMDeviceEnumerator, eConsole, eRender,
};
use windows::Win32::System::Com::{CLSCTX_ALL, CoCreateInstance};
use windows::Win32::UI::Input::KeyboardAndMouse::{
    INPUT, INPUT_0, INPUT_KEYBOARD, KEYBDINPUT, KEYEVENTF_KEYUP, SendInput, VIRTUAL_KEY,
    VK_VOLUME_DOWN, VK_VOLUME_UP,
};
use windows::core::{GUID, implement};

use crate::osd::{WindowEvent, WindowEventObserver};

const PROBE_CONTEXT: GUID = GUID::from_u128(0x4b8fc5fe_a7e1_4af5_95fc_b7e8af910fa4);

#[derive(Debug, Serialize)]
pub struct AudioProbe {
    pub initial_scalar: f32,
    pub direct_core_audio: VolumeRoute,
    pub synthetic_volume_key: VolumeRoute,
    pub restored_scalar: f32,
}

#[derive(Debug, Serialize)]
pub struct VolumeRoute {
    pub requested_scalar: Option<f32>,
    pub callback_count: usize,
    pub first_callback_ms: Option<f64>,
    pub callback_from_probe_context: bool,
    pub observed_scalar: Option<f32>,
    pub shell_window_events: Vec<WindowEvent>,
}

#[derive(Clone, Copy)]
struct VolumeNotice {
    observed_at: Instant,
    context: GUID,
    scalar: f32,
}

#[implement(IAudioEndpointVolumeCallback)]
struct VolumeNotifications {
    sender: Sender<VolumeNotice>,
}

impl IAudioEndpointVolumeCallback_Impl for VolumeNotifications_Impl {
    fn OnNotify(
        &self,
        notification: *mut AUDIO_VOLUME_NOTIFICATION_DATA,
    ) -> windows::core::Result<()> {
        if notification.is_null() {
            return Err(windows::core::Error::from_hresult(E_POINTER));
        }
        // SAFETY: Core Audio guarantees a live notification structure for this callback invocation.
        let notification = unsafe { &*notification };
        self.sender
            .send(VolumeNotice {
                observed_at: Instant::now(),
                context: notification.guidEventContext,
                scalar: notification.fMasterVolume,
            })
            .map_err(|_| windows::core::Error::from_hresult(E_FAIL))
    }
}

pub fn measure() -> Result<AudioProbe> {
    // SAFETY: the process has an initialized STA and the class and interface IDs come from bindings.
    let enumerator: IMMDeviceEnumerator =
        unsafe { CoCreateInstance(&MMDeviceEnumerator, None, CLSCTX_ALL) }
            .context("create MMDeviceEnumerator")?;
    // SAFETY: the enumerator is live and the enum values select the default render console endpoint.
    let device = unsafe { enumerator.GetDefaultAudioEndpoint(eRender, eConsole) }
        .context("get default audio endpoint")?;
    // SAFETY: IAudioEndpointVolume is a documented activation interface for an IMMDevice.
    let endpoint: IAudioEndpointVolume =
        unsafe { device.Activate(CLSCTX_ALL, None) }.context("activate IAudioEndpointVolume")?;
    // SAFETY: endpoint remains live for the duration of the call.
    let initial_scalar =
        unsafe { endpoint.GetMasterVolumeLevelScalar() }.context("read initial endpoint volume")?;

    let (sender, receiver) = channel();
    let callback: IAudioEndpointVolumeCallback = VolumeNotifications { sender }.into();
    // SAFETY: callback is a live COM implementation retained through explicit unregister.
    unsafe { endpoint.RegisterControlChangeNotify(&callback) }
        .context("register endpoint volume callback")?;

    let measured = measure_routes(&endpoint, &receiver, initial_scalar);
    // SAFETY: this unregisters the exact callback registered above while both objects remain live.
    let unregistered = unsafe { endpoint.UnregisterControlChangeNotify(&callback) }
        .context("unregister endpoint volume callback");
    let (direct_core_audio, synthetic_volume_key) = measured?;
    unregistered?;
    // SAFETY: endpoint remains live for the duration of the call.
    let restored_scalar = unsafe { endpoint.GetMasterVolumeLevelScalar() }
        .context("read restored endpoint volume")?;

    Ok(AudioProbe {
        initial_scalar,
        direct_core_audio,
        synthetic_volume_key,
        restored_scalar,
    })
}

fn measure_routes(
    endpoint: &IAudioEndpointVolume,
    receiver: &Receiver<VolumeNotice>,
    initial_scalar: f32,
) -> Result<(VolumeRoute, VolumeRoute)> {
    let observer = WindowEventObserver::install().context("install shell window observer")?;
    drain(receiver);

    let requested = if initial_scalar <= 0.98 {
        initial_scalar + 0.01
    } else {
        initial_scalar - 0.01
    };
    observer.clear();
    let direct_started = Instant::now();
    // SAFETY: requested is within 0.0..=1.0 and the event-context GUID remains live for the call.
    unsafe { endpoint.SetMasterVolumeLevelScalar(requested, &PROBE_CONTEXT) }
        .context("set direct endpoint volume")?;
    let direct_events = observer
        .collect_for(Duration::from_millis(900))
        .context("observe direct-route window events")?;
    let direct_notices = drain(receiver);
    restore(endpoint, initial_scalar)?;
    observer
        .collect_for(Duration::from_millis(200))
        .context("settle direct-route restoration")?;
    drain(receiver);

    observer.clear();
    let key_started = Instant::now();
    send_volume_key(if initial_scalar > 0.5 {
        VK_VOLUME_DOWN
    } else {
        VK_VOLUME_UP
    })?;
    let key_events = observer
        .collect_for(Duration::from_millis(1_200))
        .context("observe synthetic-key window events")?;
    let key_notices = drain(receiver);
    restore(endpoint, initial_scalar)?;
    observer
        .collect_for(Duration::from_millis(200))
        .context("settle synthetic-key restoration")?;
    drain(receiver);

    Ok((
        route(
            Some(requested),
            direct_started,
            &direct_notices,
            direct_events,
        ),
        route(None, key_started, &key_notices, key_events),
    ))
}

fn restore(endpoint: &IAudioEndpointVolume, scalar: f32) -> Result<()> {
    // SAFETY: scalar was read from this endpoint and the event-context GUID is live for the call.
    unsafe { endpoint.SetMasterVolumeLevelScalar(scalar, &PROBE_CONTEXT) }
        .context("restore endpoint volume")
}

fn send_volume_key(key: VIRTUAL_KEY) -> Result<()> {
    let press = INPUT {
        r#type: INPUT_KEYBOARD,
        Anonymous: INPUT_0 {
            ki: KEYBDINPUT {
                wVk: key,
                ..Default::default()
            },
        },
    };
    let release = INPUT {
        r#type: INPUT_KEYBOARD,
        Anonymous: INPUT_0 {
            ki: KEYBDINPUT {
                wVk: key,
                dwFlags: KEYEVENTF_KEYUP,
                ..Default::default()
            },
        },
    };
    let inputs = [press, release];
    let input_size = i32::try_from(size_of::<INPUT>()).context("INPUT size exceeds i32")?;
    // SAFETY: inputs is a live contiguous array and input_size matches the Windows INPUT ABI.
    let sent = unsafe { SendInput(&inputs, input_size) };
    if sent == u32::try_from(inputs.len()).context("input count exceeds u32")? {
        Ok(())
    } else {
        Err(std::io::Error::last_os_error()).context("SendInput volume key")
    }
}

fn drain(receiver: &Receiver<VolumeNotice>) -> Vec<VolumeNotice> {
    receiver.try_iter().collect()
}

fn route(
    requested_scalar: Option<f32>,
    started: Instant,
    notices: &[VolumeNotice],
    shell_window_events: Vec<WindowEvent>,
) -> VolumeRoute {
    VolumeRoute {
        requested_scalar,
        callback_count: notices.len(),
        first_callback_ms: notices
            .first()
            .map(|notice| (notice.observed_at - started).as_secs_f64() * 1_000.0),
        callback_from_probe_context: notices.iter().any(|notice| notice.context == PROBE_CONTEXT),
        observed_scalar: notices.last().map(|notice| notice.scalar),
        shell_window_events,
    }
}
