mod argument;
mod builtin_argument;
mod builtin_id;
mod catalog;
mod catalog_codec;
mod catalog_definition_codec;
mod catalog_error;
mod catalog_exchange;
mod catalog_offer_codec;
mod catalog_transfer;
mod codec;
mod contract;
mod control;
mod control_codec;
mod lease;
mod lease_codec;
mod submission;
mod submission_codec;

#[cfg(test)]
mod catalog_tests;
#[cfg(test)]
mod tests;

use crate::FrameKind;

pub const INVOKE_ACTION_FRAME_KIND: FrameKind = FrameKind::new(16);
pub const LEASE_INVOCATION_IDS_FRAME_KIND: FrameKind = FrameKind::new(17);
pub const INVOCATION_LEASE_REPLY_FRAME_KIND: FrameKind = FrameKind::new(18);
pub const INVOCATION_STATUS_FRAME_KIND: FrameKind = FrameKind::new(19);
pub const INVOCATION_STATUS_REPLY_FRAME_KIND: FrameKind = FrameKind::new(20);
pub const CANCEL_INVOCATION_FRAME_KIND: FrameKind = FrameKind::new(21);
pub const CANCEL_INVOCATION_REPLY_FRAME_KIND: FrameKind = FrameKind::new(22);
pub const GET_CATALOG_FRAME_KIND: FrameKind = FrameKind::new(23);
pub const CATALOG_REPLY_FRAME_KIND: FrameKind = FrameKind::new(24);
pub const INVOKE_ACTION_REPLY_FRAME_KIND: FrameKind = FrameKind::new(25);

pub use argument::ActionArgument;
pub use argument::ActionArguments;
pub use argument::ArgumentError;
pub use argument::ArgumentScalar;
pub use argument::ArgumentScalars;
pub use argument::BoundedText;
pub use argument::ChoiceId;
pub use argument::Color;
pub use argument::EntityId;
pub use argument::EntityKind;
pub use argument::EntityReference;
pub use argument::FixedDecimal;
pub use argument::ParameterId;
pub use argument::SelectorId;
pub use argument::StableIdError;
pub use argument::Unit;
pub use argument::UnitValue;
pub use argument::WindowsPathInput;
pub use builtin_argument::BuiltInAnimationPrefix;
pub use builtin_argument::BuiltInAnimationStyle;
pub use builtin_argument::BuiltInArgument;
pub use builtin_argument::BuiltInArguments;
pub use builtin_argument::BuiltInArgumentsError;
pub use builtin_argument::BuiltInAxis;
pub use builtin_argument::BuiltInBorderImplementation;
pub use builtin_argument::BuiltInBorderStyle;
pub use builtin_argument::BuiltInCursorWarpPolicy;
pub use builtin_argument::BuiltInCycle;
pub use builtin_argument::BuiltInDirection;
pub use builtin_argument::BuiltInHidingBehaviour;
pub use builtin_argument::BuiltInIdentifier;
pub use builtin_argument::BuiltInImplementation;
pub use builtin_argument::BuiltInLayout;
pub use builtin_argument::BuiltInMonocleBehaviour;
pub use builtin_argument::BuiltInMoveBehaviour;
pub use builtin_argument::BuiltInNamedAnimationStyle;
pub use builtin_argument::BuiltInNames;
pub use builtin_argument::BuiltInOperationBehaviour;
pub use builtin_argument::BuiltInParameterId;
pub use builtin_argument::BuiltInRatios;
pub use builtin_argument::BuiltInResizeStep;
pub use builtin_argument::BuiltInResizeStepError;
pub use builtin_argument::BuiltInSelector;
pub use builtin_argument::BuiltInSizing;
pub use builtin_argument::BuiltInStackbarLabel;
pub use builtin_argument::BuiltInStackbarMode;
pub use builtin_argument::BuiltInWindowKind;
pub use builtin_id::BuiltInActionId;
pub use catalog::ActionAvailability;
pub use catalog::ActionCategory;
pub use catalog::ActionDefinition;
pub use catalog::ActionDefinitionSpec;
pub use catalog::ActionOffer;
pub use catalog::ActionParameter;
pub use catalog::ActionUnavailability;
pub use catalog::ArgumentCardinality;
pub use catalog::CatalogSnapshot;
pub use catalog::ConfirmationPolicy;
pub use catalog::DynamicParameterChoices;
pub use catalog::ParameterDomain;
pub use catalog::PermittedUse;
pub use catalog::UndoPolicy;
pub use catalog_codec::CatalogCodec;
pub use catalog_error::CatalogContractError;
pub use catalog_exchange::CatalogQuery;
pub use catalog_exchange::CatalogReply;
pub use catalog_transfer::CatalogChunk;
pub use catalog_transfer::CatalogChunks;
pub use catalog_transfer::CatalogPayloadDigest;
pub use catalog_transfer::CatalogReassembler;
pub use catalog_transfer::CatalogTransferError;
pub use codec::ActionInvocationCodec;
pub use codec::CanonicalActionInvocation;
pub use codec::CommandCodecError;
pub use contract::ActionContractError;
pub use contract::ActionContractFingerprint;
pub use contract::ActionId;
pub use contract::ActionInvocation;
pub use contract::ActionKey;
pub use contract::ActionSchemaVersion;
pub use contract::CatalogStamp;
pub use contract::ConfirmationChallengeId;
pub use contract::OfferRef;
pub use contract::Revision;
pub use contract::StateStamp;
pub use control::CancelInvocationReply;
pub use control::CancelInvocationRequest;
pub use control::InvocationProgress;
pub use control::InvocationStatus;
pub use control::InvocationStatusReply;
pub use control::InvocationStatusRequest;
pub use control::InvocationTerminal;
pub use control::InvocationUnavailable;
pub use control::SettledInvocationKind;
pub use control_codec::InvocationControlCodec;
pub use control_codec::InvocationStatusCodec;
pub use lease::InvocationLeaseRejection;
pub use lease::InvocationLeaseReply;
pub use lease::InvocationLeaseRequest;
pub use lease_codec::InvocationLeaseCodec;
pub use submission::InvocationRejection;
pub use submission::InvocationSubmissionReply;
pub use submission_codec::InvocationSubmissionCodec;
