#![warn(clippy::all, clippy::pedantic)]

mod bootstrap;
mod error;
mod frame;
mod identity;
mod session;
mod version;

pub use bootstrap::BootstrapCodec;
pub use bootstrap::BootstrapCodecError;
pub use bootstrap::FeatureId;
pub use bootstrap::FeatureSet;
pub use bootstrap::FeatureSetError;
pub use bootstrap::HELLO_FRAME_KIND;
pub use bootstrap::Hello;
pub use bootstrap::PROTOCOL_FAULT_FRAME_KIND;
pub use bootstrap::RoleHint;
pub use bootstrap::UNSUPPORTED_VERSION_FRAME_KIND;
pub use bootstrap::WELCOME_FRAME_KIND;
pub use error::FrameError;
pub use frame::Frame;
pub use frame::FrameHeader;
pub use frame::HEADER_BYTES;
pub use frame::MAX_FRAME_PAYLOAD_BYTES;
pub use identity::DirectionSequence;
pub use identity::FrameKind;
pub use identity::ProtocolPreface;
pub use identity::StreamId;
pub use session::AssemblyDeadlineMs;
pub use session::AuthorityCapabilityId;
pub use session::AuthoritySummary;
pub use session::AuthoritySummaryError;
pub use session::ChunkPayloadLimit;
pub use session::ConnectionId;
pub use session::ControlPayloadLimit;
pub use session::FramePayloadLimit;
pub use session::IdentifierError;
pub use session::ManagerEpoch;
pub use session::NegotiatedProtocol;
pub use session::NegotiationError;
pub use session::NestingLimit;
pub use session::ProtocolNegotiator;
pub use session::ReassemblyLimit;
pub use session::ServerSupport;
pub use session::SessionLimitError;
pub use session::SessionLimits;
pub use session::Welcome;
pub use version::CatalogSchemaVersion;
pub use version::ProtocolMajor;
pub use version::ProtocolMinor;
pub use version::ProtocolVersion;
pub use version::VersionRange;
pub use version::VersionRanges;
pub use version::VersionSetError;
